(setq frame-inhibit-implied-resize t)
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lisp/static_packages" user-emacs-directory))

(setq tramp-mode nil)
(setq tramp-gvfs-enabled nil)

(add-hook 'after-init-hook
  (lambda ()
    (setq gc-cons-threshold 800000)
    (message "GC threshold restored to %s" gc-cons-threshold)))

(if (file-exists-p (expand-file-name "lisp/privacy.el" user-emacs-directory))
    (require 'privacy)
  (require 'privacy-example)
  (message "No privacy configuration found. "))

(require 'startup)
(require 'for_kitty)
(require 'utils)
(require 'keybindings)
(require 'packages)
(require 'file_management)
(require 'insert)
(require 'programming)
(require 'ui)
(require 'org_mode_settings)
(require 'custom)
(require 'menu&bookmark)
(require 'modes)
(require 'simpc-mode)
(require 'email)
(require 'eshell-config)
(add-to-list 'auto-mode-alist '("\\.[hc]?\\'" . simpc-mode))
