(setq frame-inhibit-implied-resize t)
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(add-to-list 'load-path (expand-file-name "lisp/static-packages" user-emacs-directory))

(setq tramp-mode t)
(setq tramp-gvfs-enabled t)

(add-hook 'after-init-hook
  (lambda ()
    (setq gc-cons-threshold 800000)
    (message "GC threshold restored to %s" gc-cons-threshold)))

(if (file-exists-p (expand-file-name "lisp/privacy.el" user-emacs-directory))
    (require 'privacy)
  (require 'privacy-example)
  (message "No privacy configuration found. "))

(require 'startup)
(require 'for-kitty)
(require 'utils)
(require 'keybindings)
(require 'packages)
(require 'file-management)
(require 'insert)
(require 'programming)
(require 'ui)
(require 'org-mode-settings)
(require 'custom)
(require 'menu&bookmark)
(require 'modes)
(require 'email)
(require 'eshell-config)
(require 'ai)
